### ISSUE TITLE
User Reporting Tools 

### ISSUE THREAD

**Issue by nmadero** [colinxfleming/dcaf_case_management#20]
Users will need different type of reporting tools based on the data collected by case manager. The reports can be either in a dashboard or even in a static report. The dashboard can display number of active cases that are available or that need to be called in queue. They can also sort by demographics/income/zip codes of all the patients in the database.

There should also be an ability to export the data in .csv where they can manipulate the data. 

The reports could be run by a individual case manager or at case manager supervisor level. At the individual case manager, they will probably want information that is related to their activity for the night or to help them manage their calls.

**Comment by colinxfleming** [comment]
To clarify the role of CSV functionality here: 

* For MVP, we'll need to be able to export data to get it into the current CM system, since we aren't planning on doing a full switchover yet. 
* For the full release, we should plan on restricting CSV export to just superusers given the sensitive nature of the data we're storing.

**Comment by colinxfleming** [comment]
I think exporting data is a feature we can skip in the short term. If we discover a need to get data out then we can investigate that. 

I think some degree of internal reporting / analytics is hugely important, but I think that it's OOS until at least December 1, and probably realistically it's a 2017 thing.

**Comment by colinxfleming** [comment]
This is underway in a separate thread -- closing out.
