### ISSUE TITLE
Status Indicator

### ISSUE THREAD

**Issue by adinneen** [colinxfleming/dcaf_case_management#202]
@lwaldsc Information on Status Indicator - Linked with DCM - 25 and DCM 27

**A DCAF Case can have 7 different statuses:** 
1) No contact made (all new entries are defaulted to this status) 
2) Needs appointment (a case that has a call log entry that says "spoken with" gets put in this status)
3) Fundraising (a case that has an appointment date AND clinic information gets put in this status)
4) Sent Pledge (a case where someone has pushed the pledge sent button)
5) Pledge Paid (a case where a financial admin person has indicated the case has been paid)
6) Inactive (a case that has been open for 6 months or more and not in statuses pledge paid or sent pledge)
7) Resolved without DCAF (a case where the case manager has selected this status from the dropdown)

@mebates We'll need to make a change to the comps to show that that status is not a field where people choose a dropdown but something that is being pre-determined.  Maybe something like this: 

![screen shot 2016-03-28 at 9 12 07 pm](https://cloud.githubusercontent.com/assets/12372787/14095018/c828976c-f529-11e5-99fd-68b0d1cc6074.png)

**Comment by mebates** [comment]
Are you thinking that the 'Urgent' label could go on any of the statuses? We have that indicated in the Notes section, not sure that it needs to be in the status too (or maybe it could be just an icon).

**Comment by colinxfleming** [comment]
Hey friends -- I'm gonna tag this admin for now while we get these questions figured out, since this isn't quite ready for programming action due to the urgent question/adjustment to the designs for Resolved Without DCAF, right?

**Comment by colinxfleming** [comment]
Re-marking as question since we have some hashing out of this to do yet!

So it sounds like based on @adinneen 's work with @lwaldsc, we're looking at status as an inferred field. NBD, that's pretty straightforward and I think it's a great idea, and a major value-add over the excel sheet!

I have two points of feedback:

* I'm a little confused about how to implement `Resolved Without DCAF`. It sounds like status as laid out here isn't a dropdown -- does this look like a checkbox somewhere? 
* It kind of sounds like `Inactive` is largely independent of status. Should we spin that off into its own inferred model field? 
* Does it make sense to make `Inactive` status-agnostic? As DCAF CMD Kate once pointed out in a much more artful way, our cases are timeboxed by biology because eventually someone will not be pregnant anymore, and probably 6 months after intake of anyone there's not going to be a lot we can do one way or the other. Maybe it's appropriate to apply this to every pregnancy?

**Comment by colinxfleming** [comment]
Urgent and Inactive should be their own independent fields, independent of status. Both can be just icons but should be somewhere on the call list labels on the front page.

Urgent should be able to be toggled by a CM but maintained as part of the PT file (so can be seen by any CM).

The only reason we highlighted Pledge Sent and Pledge Paid was to maintain an open file for DCAF financial admins coming back into the system to pay, but if the file is not going to close, I think we could make it status-agnostic and simply just a timed out flag. 

I think Resolved Without DCAF should be in the status dropdown. If a PT falls into this category, they are not going to fall into any of the others. They're mutually exclusive statuses.

**Comment by colinxfleming** [comment]
Above re: @lwaldsc @NerdyGirl537

**Comment by mebates** [comment]
Colin and I agreed that "Resolved without DCAF" would be an additional checkbox in the Notes section, like so:

![screen shot 2016-04-17 at 4 06 42 pm](https://cloud.githubusercontent.com/assets/6223901/14589692/749b0296-04b6-11e6-9517-a4719f5f238a.png)

**Comment by mebates** [comment]
Per our discussions last week about status and pregnancy date, here's what the top section might look like for a case:

![screen shot 2016-04-17 at 4 12 59 pm](https://cloud.githubusercontent.com/assets/6223901/14589737/59ebc3d0-04b7-11e6-8eef-65b6a1247bf6.png)

**Comment by colinxfleming** [comment]
Thanks for these designs, @mebates ! 

I'll change this issue to be bumping the InVision to reflect the changes, and link relevant issues to this one.

**Comment by colinxfleming** [comment]
Resolved in #252 , tests stubbed out for when we implement pledge stuff. 

This is resolved from a design and discussion perspective as well, I believe! Closing out.
