### ISSUE TITLE
Flag in readme that model changes require re-seeding

### ISSUE THREAD

**Issue by ajohnson052** [colinxfleming/dcaf_case_management#222]
When I am on the pregnancies edit form, and I use the “TEMP: Save Information” button, the request is not being completed. Although the button correctly directs to the pregnancies#update method, the data is not saving and it returns 400 Bad Request.

The “TEMP: Save Information” button should save all pregnancy information and redirect to the edit pregnancy page.

**Comment by colinxfleming** [comment]
Thanks a ton for logging this @ajohnson052 ! I'll take a look at it as soon as I can since I think it's likely a blocker on some other stuff. (Following that we should start writing up lots of integration tests to not accidentally walk our code backwards.)

**Comment by colinxfleming** [comment]
Note that this is linked to #100. Let's not consider this closed until tests are written so we don't continue to backslide.

**Comment by colinxfleming** [comment]
Adding to Sprint 4.

**Comment by colinxfleming** [comment]
@ajohnson052 Did some digging and I think this is caused by trying to save over a non-whitelisted field -- we were experiencing this issue on the case manager demo site. I managed to resolve by re-running the seed file, which is an okay solution for now since the DB is still in flux. 

Will you run `rake db:seed` to refresh your fake data and let me know if you continue to experience this issue?

**Comment by ajohnson052** [comment]
Well now I feel very silly - that seems to have fixed the problem!

**Comment by colinxfleming** [comment]
Glad (and more than a little relieved!) to hear that solves it for you! 

My takeaway from this is that the mongoid model being in flux can cause weird issues with things saving, and that we should flag in the readme (something like 'When beginning work, make sure you reset your seedfile'). Adjusting this issue accordingly.
