### ISSUE TITLE
Eliminate 'signed in successfully' notification in devise

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#290]
* What screen are you on? (ex: "My url is: ...") Dashboard, just after logging in

* What are you trying to do? (ex: "I'm trying to save a call.") I'm trying to get to work!

* What should be happening? (ex: "It should redirect me to the dashboard.") There shouldn't be a notification popping up to tell me that I signed in. It's obvious that I signed in!

* What's happening instead? (ex: "It's giving an error message.") The notification is appearing in green at the top of the page

* Please include any other information we might find useful (screenshots, error messages, etc). Thanks!

**Comment by colinxfleming** [comment]
Agree with @mebates that this is not ideal behavior. I think it's a feature of the authentication gem we use, `devise`, and I'm sure we can shut it off without too much trouble. 

Let's try to find a solution within the gem library first (maybe there's a `flash: false` we can put somewhere or something?). And let's limit to just the sign in flash message instead, and keep it for password resets etc. 

Tagging `backend` since it most likely involves rooting around in gem configs.

**Comment by colinxfleming** [comment]
(Relatedly I saw a 5m talk at RailsConf that was a guy talking about how much he hated, and I mean really hated, flash messages!)

**Comment by colinxfleming** [comment]
Resolved in #334, closing.
