### ISSUE TITLE
NOTES: Show latest notes on dashboard

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#367]
The notes function shows up on the dashboard in a column. Right now I'm only seeing fake notes, not real notes piping in. Do we have it rigged up so that a portion of the latest note shows in the dashboard view?

**Comment by colinxfleming** [comment]
Not currently, and we should add it! 

Here's the relevant portion of the design: 

![image](https://cloud.githubusercontent.com/assets/3866868/15985815/16fbfa94-2fbf-11e6-80b9-6d7be12b0d6c.png)

I think we'll call this resolved when: 
* The last note taken renders where the placeholder is now. We should define this with a model method on `Patient` or `Pregnancy`, something like `Pregnancy#last_note` or `Patient#last_note`.
* We should have the note trail off rather than overflow (for example, the trail-off on the second item). We can either do this with a css attribute or a model method (`last_note_display`? `last_note_abbreviated`?) that just displays the first n characters.
* We should add that gray plus sign. The behavior of the grey plus sign should pop up a tooltip with the full note text. No need to reinvent the wheel here, so let's use what's built into bootstrap for the tooltip js -- http://getbootstrap.com/javascript/#tooltips . 
* Let's make sure to test any model methods that get written that come out of this; to make sure they work and return the values we expect.
* Let's make sure to also write an integration test to confirm that an abbreviated version of the last note displays, and that the tooltip works and displays the full note.

**Comment by colinxfleming** [comment]
Tagging frontend, since these are mostly frontend issues.
