### ISSUE TITLE
Reach out to Consultant for Security Review

### ISSUE THREAD

**Issue by ewiggins** [colinxfleming/dcaf_case_management#371]
See @ewiggins for contact information. Consultant graciously offered to review our application for security vulnerabilities. We need to reach out to him.

**Comment by colinxfleming** [comment]
Probably the bulk of our vulnerabilities are going to be linux/devops based rather than application based (s/o to the team for writing good code!), so I think we can do this on the sooner side and it'll be perfectly fine. 

@ewiggins do you want to to take a stab at drafting an email to the consultant?

**Comment by ewiggins** [comment]
@colinxfleming Yep!

Hello Mike,

It was great to meet you at the DCRUG Meetup. I enjoyed your presentation.

Thank you for offering to review the DCAF Case Managment app. We've already done most of the groundwork adding Brakeman to our Gemfile, and creating an issue to run through the OWASP Ruby and Rails Guides, but any advice you can give would be magnificent!

Here is a link to our Github: https://github.com/colinxfleming/dcaf_case_management.git

What do you need from us to begin the review?

Best,
Elisheba Wiggins

**Comment by ewiggins** [comment]
@colinxfleming Reached out. Consultant reviewing, and will enter issues.

**Comment by colinxfleming** [comment]
You're a gem -- thanks Elisheba!
