### ISSUE TITLE
Make new patients show up in the call list after creation

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#398]
After creating a new patient using the build call list function, the new patient does not show up in "your call list."

**Comment by colinxfleming** [comment]
Another great ux insight from @eheintzelman -- after a user creates a new patient, we should automatically add them to the call list, since there isn't really a scenario where we make a new patient and then don't try to call them.

The task here is to edit the pregnancy create route so that this action takes place.
