### ISSUE TITLE
Change Patient#secondary_person and Patient#secondary_phone fields

### ISSUE THREAD

**Issue by eheintzelman** [colinxfleming/dcaf_case_management#402]
Should secondary person and secondary phone number be placed in a less prominent position on the layout?  As it is, it appears whether age, race/ethnicity, city, state etc. are descriptors for the patient or for the secondary person.

**Comment by colinxfleming** [comment]
@mebates gonna let you handle this one!

**Comment by mebates** [comment]
Ahh okay so this got misinterpreted from design to code. The original design's intent had a _duplication_ of the First/Last name and phone of the patient and then a secondary phone for that person. 

Original Design:
![image](https://cloud.githubusercontent.com/assets/6223901/16398777/fa273116-3c9a-11e6-906d-6606c19be9ce.png)

I suggest two possible solutions:
1) Match the original design and make the duplicate fields autopopulate
2) Eliminate the duplicate fields so the first field on 'Patient information' is 'Secondary phone.'

We didn't design a way to designate a secondary person in the app. If that's necessary, we can think of a totally different solution.

**Comment by eheintzelman** [comment]
Based on the usability tests yesterday, it seems important to be able to designate a secondary person in cases where a mother or grandmother or other person makes the arrangements for a patient.  And that is the person that the CM should be in contact with.  But the CMs didn't like the term "secondary person".  One CM suggested 'Primary Contact (if not the patient)"

**Comment by colinxfleming** [comment]
I think `Primary contact (if not the patient)` will work nicely. This will wind up being just a matter of altering the label on the form at minimum, and probably some trivial backend work to reflect the new nature of the field. Changing this to `backend`/`deploy`.

Action items for the person that takes it on: 
* Adjust the `Patient` model; change `secondary_person` to `other_contact`, and `secondary_phone` to `other_phone`
* Adjust the form fields in `app/views/pregnancies/_patient_information.html.erb` to reflect the changed field names
* Adjust the label for `other_contact` to read `Primary contact (if not the patient)`
* Fix up any tests that fail because of the field change

**Comment by colinxfleming** [comment]
(@eheintzelman @mebates let me know if any of that should be adjusted.)

**Comment by mebates** [comment]
Sounds fine to me. We can adjust in the future if it's not working for CMs.
