### ISSUE TITLE
Update seedfile 

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#515]
After the pilot we should update the seed file to reflect actual scenarios, for better testing.

**Comment by colinxfleming** [comment]
Promoting to active -- key to developer happiness

Cases to build seeds around:

* At least one patient should have `other contact` information (name, phone, and relationship)
* At least one patient should have an appointment a week from the current date and have a clinic selected
* At least one patient should have a pledge submitted
* At least one patient should be marked resolved without DCAF
* At least one patient should have special circumstances
* All patients except one or two should have notes
* Patients should have names that reflect what we're looking for (e.g. 'Patient With Other Contact' rather than 'Patient 2')

**Comment by karldonus** [comment]
I'm going to take a swing at this issue.

**Comment by jasonallenphotography** [comment]
Completed, to be pulled with @lomky:
- [x] At least one patient should have other contact information (name, phone, and relationship)
- [x] At least one patient should have an appointment a week from the current date and have a clinic selected

To do still, WIP:
- [ ] At least one patient should have a pledge submitted
- [ ] At least one patient should be marked resolved without DCAF
- [ ] At least one patient should have special circumstances
- [ ] All patients except one or two should have notes
- [ ] Patients should have names that reflect what we're looking for (e.g. 'Patient With Other Contact' rather than 'Patient 2')

Also completes #586

**Comment by colinxfleming** [comment]
@jasonallenphotography how's this coming? Anything I can do to give this a shove forward?

**Comment by jasonallenphotography** [comment]
@colinxfleming Sorry for the delay on this one! Will work on this tonight and prepare for PR by lunch tomorrow at latest.

**Comment by jasonallenphotography** [comment]
Issue #515 goals completed, but some hiccups with tests locally - will see if I can resolve before submitting pull request for review!

**Comment by colinxfleming** [comment]
@jasonallenphotography if you get stuck, just chuck up the PR and we can hash it out as a team

**Comment by jasonallenphotography** [comment]
Testing hiccups seemed to be a local issue with Mongo/mongoid, which I've resolved by restarting. 0 flunks now, PR is in!
