### ISSUE TITLE
Ongoing thread for user feedback

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#614]
Now that we've started to use this in production, we're going to spin up this issue to start keeping tabs on user feedback. We can use this to inform future dev priorities, changes, etc. 

Our first run is by Dee, call notes from night 1 are as follows:

* Words used to describe initial use: 'intuitive', 'got everything' (no action)
* activity: fairly heavy call load, sent several pledges (no action)
* felt the pledge behavior was a little confusing -- tough to follow that it doesn't autopopulate in the modal until reload, not clear what the relationship between the 'hard pledge' and the 'soft pledge' was. This is a concept that's drilled into CMs that we don't really track as much in this system. ( #630 )
* Dee noticed that adding new people to the call list didn't throw them at the top or bottom, but somewhere in the middle, which seemed a little jarring ( #653 )
* Said the tabs were very useful! Was excited that everything was saving so cleanly (no action, but nice to hear)
* Wasn't quite sure what the income field was for -- it's used mostly for determining whether or not someone's NAF eligible, but Dee pointed out (in so many words, she's much too nice to say this) that it wasn't terribly clear about that. This is probably a +1 for helper text (#460)
* Toward the end of the conversation Dee said it would be nice to have some representation of what she did over the course of the evening -- her point of reference was a facebook activity feed. This seems to stem from a concern that the call list being cleared would run the risk of people falling through the cracks. For all the things we hate about the spreadsheet it does make history accessible. (#654)

**Comment by colinxfleming** [comment]
Night 2 with Dee: 

* 'Way better today now that I'm used to it!' Observed that she was able to get through calls much faster
* Said it wasn't terribly clear why sending a pledge didn't remove the patient from the urgent cases or call list -- reasoning being that usually when we send a pledge, that's it unless we hear from them again
* With respect to default voicemail, she said that generally if someone doesn't specify she tends to err on the side of not calling. Didn't find the default setting of 'voicemail okay but don't identify' to be particularly helpful
* At one point, she accidentally removed someone from her call list and she had to go back into the system to restore it. Suggested that some kind of safety valve would be helpful
* She got a lot of mileage out of drag and drop. Spends time entering patients from the voicemail and taking notes, then moving on to the next, then ordering patients in descending order of urgency (later patients up top, later appointments down bottom).
* Said that she observed that the submit pledge checkbox was blank so she couldn't check it off, but that it fixed itself on reload. **Potential bug.**
* Dee loooooves the notes function. Said she would take running notes while taking calls. Averages 2-3 notes per call, plus a note or two from initial entry.

**Comment by colinxfleming** [comment]
cc @lwaldsc @mebates @eheintzelman

**Comment by lwaldsc** [comment]
Night 3 with Dee: 

- had a PT with multiple numbers. Reiterated the need to have the alternate number on the call popup, but told her it was in the pipeline. 
- need the ability to store more than two phone numbers? how do we want to deal with that?
- include income by month (as well as week) as that's how most PTs will discuss their income
- how will CMs learn about changes to the system as they happen? we discussed that changes will be integrated into the user manual as well as a running release changes.

Otherwise, Dee said everything is running really well and she loves using the system!

**Comment by lwaldsc** [comment]
Night 1 with Katelyn: 

- CMs should ideally have access to the cheat sheets in Crypto via the CM App. This applies mostly to the other funds we work with and the contact/pricing list for clinics. 
- She said she really appreciated how the system simplified the actual call process.
- Still wrote out notes by hand but is trying to force herself to rely on the "Your Call List" function.
- Was confused about Colin's initial password email, so he is sending a prep email before the secure email

Overall, really positive feedback with very few issues.

**Comment by lwaldsc** [comment]
Night 4 with Katelyn:

Overall, still very positive feedback

- Your Call List is still repopulating every day with seemingly little reason between PTs. She has seen PTs she has left a VM for, those still in the fundraising status, those marked resolved without DCAF, and a PT where another CM has sent a pledge already.
- Sending a pledge does not unmark a PT as urgent automatically. Both Katelyn and I feel this should be done. Is this something we could get by the next release @colinxfleming ?
- She still needs to refresh PT screen before submitting pledge to have correct amount populate in the pledge form.
- She would like a feature where a PT can be moved from the Completed List back up to Your Call List without manually having to search for the PT again. Again, is this something we could get by the next release @colinxfleming @mebates ?

**Comment by colinxfleming** [comment]
First dupe! Got an email from Katelyn as follows: 

> Hey Colin- just ran into this problem and didn't want to forget: There is no alert for when a # is duplicated when creating a new PT. If you don't search by # it doesn't alert you they are already in the system (and if you spell a PTs name wrong ☺ ) Just ran into the issue when searching by phone number and saw two entries for the same PT.

**Comment by lwaldsc** [comment]
Night 7 with Katelyn:

- As stated above, no control for duplicate numbers!
- Found a few PTs which had not been entered in the system but handled the cases just fine.
- Has stopped using paper notes!

Her handoff emails:
-Was very short as she had no outstanding PT issues. 
- Used budget tracker rather than system to indicate soft pledges (Indicating soft pledges is something that would be useful in the future, but not sure exactly how we would do that. Something to discuss between @NerdyGirl537 and the UX/design team)
-Noted it was very useful to know the urgent cases from the previous CM

Overall, really great experience. Enthusiastic about using the system and very positive.

**Comment by lwaldsc** [comment]
Joy - 

She found actual calls went much smoother and it was easier to talk with PTs; she could focus on actual conversation than messing around with spreadsheet. This also made collecting data easier as it was right in front rather than having to scroll through the spreadsheet. 

- Calendar icon with no pop up is confusing - Should we remove?
- Notes on main dashboard sometimes pops up on hover, but not all. All will pop up on click. 
- The note + is somewhat difficult to pinpoint where exactly to click - possibly make bigger?
- Confused on the language on the neutral VM status (specifically the "VM ok," which could be confused for "VM ok, ID ok"
- Need to add "Medical/Health issues" to the special circumstances (should be an easy fix, @mebates)
- She noted that sometime the "Urgent Cases" heading will be missing. She couldn't figure out what was triggering it. (She is using the current edition of Firefox on Windows 7)
- The "refresh pt file to get the pledge amount to populate in the pledge box" issue was flagged as well as sometimes the clinic name would not populate.
-When she logged a call, it would sometime not automatically log into the PT file. It would show up when she refreshed a file or went back from the dashboard. (She noted that she never lost data, just had to refresh the PT file often)
- Noted we should have a hard pledge box as well as a soft pledge box.
- Again noted that her completed calls would pop back into her call list the next day rather than clearing out.
- She recommended we add an appointment date column to the dashboard to make it easy to arrange the call list by who will need their pledge soonest. [@lwaldsc: If we have the room, I think this would be a great addition.]
- Would like the dashboard autosortable by the column headers.
- Add the ability to create a new record when there are some search results.  Currently, you only get the "add a new patient" dialogue when the search comes up with nothing.  But CMs should be able to search by a partial search and still be able to add a PT if a search returns other PTs. 
-Would love the ability to edit notes
-Make a way to move someone from completed calls back to Your Call List. If she left a message for a PT and wanted to retry the PT later or the PT called her back, she was unable to search for the PT until she removed the PT from the Completed Call list.

**Issue she flagged which I think we need to address is the scenario where a PT will give an apt date in the voicemail, but we may not actually contact the PT. If the CM fills in the appointment date, the PT's status will be fundraising, regardless if we have ever talked to them. It is rare of enough an occasion, we may not have to do anything, but just want to flag that. cc: @colinxfleming @NerdyGirl537** 

We've talked about possibly having a feature where a CM's stats (how many calls, how many pledges, etc, in a certain time period) but she added this: "This is another one that's probably very long term, but I would really like to be able to search for my own notes (perhaps within a date range).  Sometimes I get really involved with a patient and want to come back after my shift to see if she was able to get taken care of, but it is hard to remember names or phone numbers.  I'd like to be able to check back on "my" patients." Don't know if this would pose security issues, but a thought.

Also flagged that there are situation where a PT will use several numbers and if a CM does not spell the name correctly, that PT will not show up and not catch the number dup check. Not sure how we'd work this one out, maybe some sort of fuzzy search, but it does happen.

She also gave the highest compliments to Mollie and the design team for making everything very intuitive with very little of a learning curve.

**Comment by NerdyGirl537** [comment]
Just did a quick read. The one you asked to flag is actually not an issue.
I did this for over 100 patients on data entry. They stay in no contact
made until you click the I reached patient button.

**Comment by lwaldsc** [comment]
Ari - 
- Still having issues with completed calls resetting into her call list the next day.
- Needs more than one alt phone number slots
- Seconds need for a fuzzy search; she flagged that many PTs give their number late in the voicemail
- Wondering if there was a way for CMs to flag a PT for admin review for some reason (the example she gave was duplicate records, but there could be other uses for this feature)

- Also flagged a desire to have more slots for different funding sources (other funds) and the information cheat sheets somewhere in the system, but we discussed they are planned for upcoming releases.

Overall, really positive feedback similar to the other case managers.

**Comment by lwaldsc** [comment]
Arona-

- "Resolved without DCAF" PTs are popping back into call list, in addition to others
- Would like appointment date on the Your Call List details so CMs can sort PTs by closest appt date
- Drag and drop was not working smoothly for her (Firefox 48.0.2/Windows 10)
- Asked for a button to call a PT from inside the PT file. After looking at the system today, it looks like there is one, but not sure when it was added or if it's a case of not being easy for the CMs to find.

She also asked if there was a way to see if there are any outstanding soft pledges when we work on the budget tracker. The example she gave was if she is at the end of the week and it's been very slow, she will follow up with soft pledged PTs to see where they are in funding and if she can fill their gap (while staying within rules/budget, obviously).

Other CMs have mentioned desires to see what has happened on the line this week or who is being soft pledged for similar reasons. Not sure how we work this request, but something to think about moving forward!

**Comment by NerdyGirl537** [comment]
This has been banging around in my brain all week and I'm pretty sure I
read it wrong.  Definitely should check it out.

**Comment by colinxfleming** [comment]
Have logged issues thru Joy. Will be continuing work shortly.

**Comment by lwaldsc** [comment]
First round of user feedback completed. Will start making issues from specific feedback. 

Thanks!

**Comment by colinxfleming** [comment]
💯 

Actionable issues here are spun out. @lwaldsc , want to reiterate that you did an absolutely outstanding job of collecting and logging all this, and that the changes represented here are going to have the net effect of a massive CM experience improvement. Outstanding work.
