### ISSUE TITLE
Remove calendar icon from appointment date field?

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#660]
placeholder from #614 until we figure out how to deal

**Comment by lwaldsc** [comment]
Just bumping this issue because we've gotten more feedback that folks are confused and expecting a dropdown to work.

cc: @mebates

**Comment by colinxfleming** [comment]
Thanks for flagging, @lwaldsc . Tagging in team ux to figure out how to handle (though I'll also skim the issues this weekend and make sure we haven't made a decision on this already).

**Comment by mebates** [comment]
I would suggest improving the date field by making it MM-DD-YYYY. Remove the calendar icon unless it will be an active calendar picker. The picker is not necessary; tabbed date entry is probably more important since the PT will likely be telling the CM the date. The only use for calendar picker is if the PT says something like "next Wednesday".

**Comment by colinxfleming** [comment]
MM-DD-YYYY hurts my heart as a lifelong lover of the ISO standard (perhaps my nerdiest, most terrible opinion) but I think @mebates is right on all counts here. I'll spin up an issue to standardize date entry as MM-DD-YYYY, and in the immediate term let's **remove the calendar icon**.

**Comment by lwaldsc** [comment]
@colinxfleming 
https://media.giphy.com/media/OMK7LRBedcnhm/giphy.gif

**Comment by janinedog** [comment]
I'll give this one a try.  :)
