### ISSUE TITLE
ACCOUNTING: Make patient identifier searchable

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#727]
Right now we have patient identifier as a method that's inferred from a patient's `line` and `primary_phone_no`. Our accountant primarily works with those identifiers, so we're going to want to incorporate that into our search functionality -- e.g. I should be able to enter `D3-1122` and have it return the patient with that identifier. 

Here are two options:
* persist as a db field that gets populated after save -- e.g. something like `after_save :update_patient_identifier, if: :primary_phone_or_line_changed?` plus associated model changes
* bolt something on to our existing search method that is smart enough to parse entering patient codes. If there's an easy way to do this, sweet -- if not let's not worry about it.

Either is perfectly fine with me. Developer's choice! 

This is requested by our accountant user and stems from needs in #643

**Comment by DarthHater** [comment]
A few things on patient identifier, it's always a combination of those two fields? Is there a potential for them to be non unique (two patients could have the same identifier by accident because they share common fields that make it happen)?

Since it uses last five of phone number I could see it happening, if they shared line all you would need is two people in DC who have 11234 as their last five, right? Not the most common of occurrences for sure but it just feels weird to me allowing for such a case to occur. 

(If I'm overthinking this tell me) @colinxfleming @vtmeghan

**Comment by colinxfleming** [comment]
@DarthHater just in case we never closed the loop on this -- I think the right way to do this is to ensure that the way we generate or infer a patient identifier is a standalone method, so we can pop it out with something better. I'll hit up DCAF's CMDs about this separately and we can spin that part of it into a separate method. Thanks for flagging this -- let me know if I can do anything else to unstick.

**Comment by lwaldsc** [comment]
I definitely don't think we're married to using PT phone number based ID at all. I am 100% behind another unique identifier. 

As said, it may also help us for the few times there are different PTs with the same number. As long as we keep some sort of safeguard against multiple entries for one PT (not exactly we want to do here).

**Comment by NerdyGirl537** [comment]
I think the issue here is referring to it as a "unique" identifier.  The idea of the identifier is to mask part of the PPI while providing enough information, when combined with the patient name, to make sure the correct pledge is being paid.  So think of it as a coded identifier rather than a unique one.  Thoughts?

**Comment by DarthHater** [comment]
@NerdyGirl537 yeah, I get that. I'm referring to it as unique as if it's searchable, you could technically get two if you were using the identifier, potentially causing some UX issues, blah blah blah.

**Comment by NerdyGirl537** [comment]
@DarthHater I think it would be fine to return all matching and let the accountant find it.  Honestly, I'm not even sure we need to store the identifier, given we have a really smart partial look up on the phone number.  It just needs to be used to protect the information on the pledge form.  The accountant could just login by the phone line indicated (D/M/V) and then use the partial look up to find the patient.  Thoughts?

**Comment by DarthHater** [comment]
I'm fine with whatever, just wanted to call out the potential issues. I'll try and crack at this a bit later today.

**Comment by Kevin-Wei** [comment]
Heres an attempt https://github.com/colinxfleming/dcaf_case_management/pull/821
