### ISSUE TITLE
Fix spacing on call list

### ISSUE THREAD

**Issue by mebates** [colinxfleming/dcaf_case_management#781]
The call list is very cramped and difficult to read. It needs margins between each column, and some massaging of column widths. Work directly with me to fix this. 

![screen shot 2016-12-12 at 12 02 16 pm](https://cloud.githubusercontent.com/assets/6223901/21108402/feb9050a-c062-11e6-928a-925076b9e036.png)

**Comment by AlexandraCasser** [comment]
@mebates are you working on this?  If not I'd like to take it!

**Comment by mebates** [comment]
@AlexandraCasser - please do! I'm the designer so I can consult with you as you develop.

**Comment by lwaldsc** [comment]
Just a thought, @Mebates, but could the "remove" just be a 🚫 or something
similar with a hover over text "Remove from call list"? Might give us a
spare few pixels.

On Fri, Jan 13, 2017 at 11:33 AM, Alexandra Casser <notifications@github.com

**Comment by AlexandraCasser** [comment]
@lwaldsc I think that's a really good idea.

@mebates How does this look to you?  I added some more padding to the table cells and thought we could fill in every other column to make it easier to differentiate.  
![screen shot 2017-01-13 at 12 28 53 pm](https://cloud.githubusercontent.com/assets/12383179/21939041/ff454870-d98b-11e6-9258-01f51966258f.png)

**Comment by mebates-USDS** [comment]
Thanks @AlexandraCasser ! 
- I think the filled columns distract from the rows; if anything I would fill in by row
- If you abbreviate "Appointment Date" to "Appt Date" you'll have more space in that column. 
- Phone should definitely stay on one line; that is a fixed width
- LMP also feels like it should be on one line too
- Notes column can get narrower so other things can fit on one line
- Don't mind if name is two lines
- 'Remove' can be an X in a circle in red instead of the word "Remove"; that will give you more space too. Would be great if on hover it said "Remove from call list"

**Comment by AlexandraCasser** [comment]
- [ ] I think the filled columns distract from the rows; if anything I would fill in by row
- [ ] If you abbreviate "Appointment Date" to "Appt Date" you'll have more space in that column.
- [ ] Phone should definitely stay on one line; that is a fixed width
- [ ] LMP also feels like it should be on one line too
- [ ] Notes column can get narrower so other things can fit on one line
- [ ] Don't mind if name is two lines
- [ ] 'Remove' can be an X in a circle in red instead of the word "Remove"; that will give you more space too. Would be great if on hover it said "Remove from call list"

**Comment by colinxfleming** [comment]
Fixed by #827
