### ISSUE TITLE
Perform Validation on the Add Patient From Prior to Submit.

### ISSUE THREAD

**Issue by kscoulter** [colinxfleming/dcaf_case_management#784]
Perform front-end validation on the new patient form. It can be frustrating to fill out the form and lose all that information because an extra number has snuck into the phone number. Some HTML5 form elements already come with validation.

**Comment by colinxfleming** [comment]
tagging in @Kevin-Wei

**Comment by colinxfleming** [comment]
This is absolutely dead on and very insightful. Here are two possibilities in order of complexity:

* on failure, render new and have some errors populate (this might not work since we don't prerender the new patient partial)
* switch this to some ajax that renders error messages and prevents the form from submitting if it doesn't pass validation, and creates the patient, clears the create call, and re-renders call list. Probably we can do this by changing the controller failure condition around.

The latter is something we're hoping to implement in a few other places across the app, so frankly if we can get that to work then it's a significant leap forward and can be adapted in a few other places.
