### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by DarthHater** [colinxfleming/dcaf_case_management#791]
In keeping up with the internet, it would be wise to upgrade to Rails 5. The biggest issue thus far is auth0 (a contender for SSO) requires Rails 5.

**Comment by colinxfleming** [comment]
Since we have such a rigorous test suite, probably this is mostly getting the libraries in agreement so that we can do basic stuff like `rails test`, `rails db` stuff, `bundle install`, etc. Given that most of the stuff we used was engineered for rails 4, this might be kind of a pain (as @DarthHater can attest). 

Here's the rails guide: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html

**Comment by DarthHater** [comment]
Path paved a bit by the work in #853 #955 and #959 , picking this back up this week in either #865 or a new PR based off master
