### ISSUE TITLE
Break out readme into wiki pages

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#813]
Per discussion at a hacknight in December with @lomky and @Kevin-Wei : Our readme is great but it's too long. We should break stuff like setup etc into individual pieces in the wiki.

**Comment by stvnrlly** [comment]
Another approach is to use a `docs` folder and link to the files within it from the readme. I personally like that approach because it keeps the documentation with the project; I feel like wikis are more likely to drift apart from the code since you can't update the wiki as part of your feature branch.

**Comment by DarthHater** [comment]
Agree with @stvnrlly here, I mostly see Wiki's used for Roadmap, etc... and Docs living in the code base (impetus to update them, review them, etc...)
