### ISSUE TITLE
Google SSO test passes with bad value

### ISSUE THREAD

**Issue by krisudekwu** [colinxfleming/dcaf_case_management#839]
I was working with @DarthHater and he was showing me testing. As we were working, we found that changing the value in the Google SSO test did not cause the test to fail.

¯\_(ツ)_/¯

Command to run test:

rake test TEST=test/integration/google_sso_test.rb

Offending code:

https://github.com/colinxfleming/dcaf_case_management/blob/master/test/integration/google_sso_test.rb#L12

**Comment by colinxfleming** [comment]
hey @krisudekwu ! That link points to this line -- 

```
page.has_content?('Sign in with Google')
```

What that's doing is overcoming some capybara slowness. Capybara by default waits a few seconds for an element to appear, but sometimes jumps the gun, especially in CI environments. So to work around that, something we do is to use the command `has_content? 'text'`, which makes capybara sleep until it sees that text appear. If we take that out or even change it to something else, it won't fail the tests, because it's not associated with an `assert`. If we changed the text of the `click_link` below it, however, it would choke, because there isn't a link called that.

We have a convenience method in `test_helper` for just this case, but I agree that as written it isn't terribly clear. I'll spin up a PR to make it clearer so we can reduce the code smell a little bit.
