### ISSUE TITLE
Setup instructions are divided into two locations

### ISSUE THREAD

**Issue by ashlynnpai** [colinxfleming/dcaf_case_management#875]
The first part of the setup instructions are in the main readme under "Setting Stuff Up" and then moves to the setup.md file. It would help if they could all be in one place or if there was something in the setup.md file directing users to look at the "Setting Stuff Up" section first.

Also for the Cloud 9 instructions it would be helpful to explain to users how to kill mongo when you are done.

**Comment by colinxfleming** [comment]
@ashlynnpai I really, really appreciate your documenting this. (PS sorry I missed you tonight -- glad to have you back!)

I think this is a great observation and we should 100% do both of these things. Let me know if there's a PR in the works for this, otherwise I'll plan on knocking it over this wknd.

**Comment by ashlynnpai** [comment]
@colinxfleming I haven't done anything towards fixing this issue, it sort of just "came up" last night.  Thanks!
